openapi: 3.1.0
info:
  title: ""
  version: 0.0.1
security:
  $include: ./security.yml#/security
tags:
  - $include#chat: ../../src/services/chats/chats.spec.yml#tags/0
  # $include#documents: ../../src/services/documents/documents.spec.yml#tags
  - $include#tool: ../../src/services/tools/tools.spec.yml#tags/0
  # $include#user: ../../src/services/users/users.spec.yml#tags
  # $include#upload: ../../src/services/uploads/uploads.spec.yml#tags
paths:
  $include#chat: ../../src/services/chats/chats.spec.yml#paths
  # # $include#document: ../../src/services/documents/documents.spec.yml#paths
  $include#tool: ../../src/services/tools/tools.spec.yml#paths
  # # $include#user: ../../src/services/users/users.spec.yml#paths
  # # $include#upload: ../../src/services/uploads/uploads.spec.yml#paths
components:
  securitySchemes: {}
  requestBodies: {}
  responses:
    $include#chat: ../../src/services/chats/chats.spec.yml#/components/responses
    # # $include#document: ../../src/services/documents/documents.spec.yml#/components/responses
    $include#tool: ../../src/services/tools/tools.spec.yml#/components/responses
    # # $include#user: ../../src/services/users/users.spec.yml#/components/responses
    # # $include#upload: ../../src/services/uploads/uploads.spec.yml#/components/responses
  examples:
    $include#chat: ../../src/services/chats/chats.spec.yml#/components/examples
    # # $include#document: ../../src/services/documents/documents.spec.yml#/components/examples
    $include#tool: ../../src/services/tools/tools.spec.yml#/components/examples
    # # $include#user: ../../src/services/users/users.spec.yml#/components/examples
    # # $include#upload: ../../src/services/uploads/uploads.spec.yml#/components/examples
  schemas:
    $include#errors: ./errors.yml#/components/schemas
    $include#shared: ./shared.yml#/components/schemas
    $include#chat: ../../src/services/chats/chats.spec.yml#/components/schemas
    # # $include#document: ../../src/services/documents/documents.spec.yml#/components/schemas
    $include#tool: ../../src/services/tools/tools.spec.yml#/components/schemas
    # # $include#user: ../../src/services/users/users.spec.yml#/components/schemas
    # # $include#upload: ../../src/services/uploads/uploads.spec.yml#/components/schemas

