openapi: 3.0.0
info:
  title: ""
  version: 0.0.1
security:
  - bearerAuth: []
  - $ref#1: ../../src/services/chats/chats.spec.yml#/security
  - $ref#2: ../../src/services/tools/tools.spec.yml#/security
tags:
  - $ref#chat: ../../src/services/chats/chats.spec.yml#tags/0
  - $ref#tool: ../../src/services/tools/tools.spec.yml#tags/0
paths:
  $ref#chat: ../../src/services/chats/chats.spec.yml#paths
  $ref#tool: ../../src/services/tools/tools.spec.yml#paths
  $ref#chats: ../../src/services/chats/chats.spec.yml#paths
  $ref#chunks: ../../src/services/chunks/chunks.spec.yml#paths
  $ref#documents: ../../src/services/documents/documents.spec.yml#paths
  $ref#parser: ../../src/services/parser/parser.spec.yml#paths
  $ref#tools: ../../src/services/tools/tools.spec.yml#paths
  $ref#uploads: ../../src/services/uploads/uploads.spec.yml#paths
  $ref#users: ../../src/services/users/users.spec.yml#paths
  $ref#utils: ../../src/services/utils/utils.spec.yml#paths
components:
  securitySchemes:
    $ref#chats: ../../src/services/chats/chats.spec.yml#/components/securitySchemes
  requestBodies: {}
  responses:
    $ref#chat: ../../src/services/chats/chats.spec.yml#/components/responses
    $ref#tool: ../../src/services/tools/tools.spec.yml#/components/responses
    $ref#chats: ../../src/services/chats/chats.spec.yml#/components/responses
    $ref#chunks: ../../src/services/chunks/chunks.spec.yml#/components/responses
    $ref#documents: ../../src/services/documents/documents.spec.yml#/components/responses
    $ref#parser: ../../src/services/parser/parser.spec.yml#/components/responses
    $ref#tools: ../../src/services/tools/tools.spec.yml#/components/responses
    $ref#uploads: ../../src/services/uploads/uploads.spec.yml#/components/responses
    $ref#users: ../../src/services/users/users.spec.yml#/components/responses
    $ref#utils: ../../src/services/utils/utils.spec.yml#/components/responses
  examples:
    $ref#chat: ../../src/services/chats/chats.spec.yml#/components/examples
    $ref#tool: ../../src/services/tools/tools.spec.yml#/components/examples
    $ref#chats: ../../src/services/chats/chats.spec.yml#/components/examples
    $ref#chunks: ../../src/services/chunks/chunks.spec.yml#/components/examples
    $ref#documents: ../../src/services/documents/documents.spec.yml#/components/examples
    $ref#parser: ../../src/services/parser/parser.spec.yml#/components/examples
    $ref#tools: ../../src/services/tools/tools.spec.yml#/components/examples
    $ref#uploads: ../../src/services/uploads/uploads.spec.yml#/components/examples
    $ref#users: ../../src/services/users/users.spec.yml#/components/examples
    $ref#utils: ../../src/services/utils/utils.spec.yml#/components/examples
  schemas:
    $ref#errors: ./errors.yml#/components/schemas
    $ref#shared: ./shared.yml#/components/schemas
    $ref#chat: ../../src/services/chats/chats.spec.yml#/components/schemas
    $ref#tool: ../../src/services/tools/tools.spec.yml#/components/schemas
    $ref#chats: ../../src/services/chats/chats.spec.yml#/components/schemas
    $ref#chunks: ../../src/services/chunks/chunks.spec.yml#/components/schemas
    $ref#documents: ../../src/services/documents/documents.spec.yml#/components/schemas
    $ref#parser: ../../src/services/parser/parser.spec.yml#/components/schemas
    $ref#tools: ../../src/services/tools/tools.spec.yml#/components/schemas
    $ref#uploads: ../../src/services/uploads/uploads.spec.yml#/components/schemas
    $ref#users: ../../src/services/users/users.spec.yml#/components/schemas
    $ref#utils: ../../src/services/utils/utils.spec.yml#/components/schemas
