file: default.yml
host: localhost
port: 3030
public: "./public/"
origins:
  - http://localhost:3030
paginate:
  default: 10
  max: 50

# DATABASE
postgresql:
  client: pg
  connection:
    host: localhost
    user: unicorn_user
    password: magical_password
    database: rainbow_database
    port: 5432
  pool: 
    min: 0
    max: 10
    idleTimeoutMillis: 5000
  #   createTimeoutMillis: 30000
  #   acquireTimeoutMillis: 60000
  debug: false
  automigrate: false
  autoseed: false

# API KEYS
openai: 
  key: sk-XXXXXXXXXXXXXXXXXXXXXXXXXXX
  # MODEL OPTIONS
  max_tokens_llm: 4000
  use_proxy: false
  proxy_port: 8888

# TESTING
debug: false
verbose: false

chunks:
  maxLength: 2000
  overlap: 300
  size: 2000

storage:
  bucket: sample-bucket

uploads:
  embeddingModel: text-embedding-3-small 

plugins:
  failOnImportError: true
  path: ../plugins
  start: index.js
  default:
    # - armdEBooks:
    #     path: ../plugins
    #     start: index.js
    - casHIT
    - casScamper
    - casScenarios
    - searchSemanticScholar
  restricted:
    # - searchPatents
  development:
    - devGetWeather

    

authentication:
  entity: user
  service: users
  secret: XXXXXXXXXXXXXXXXXXXXXXXXXXX
  authStrategies:
    - googleIAP
  googleIAP:
    emailField: email
    idField: googleId