file: default.yml
host: localhost
port: 3030
public: "./public/"
origins:
  - http://localhost:3030
paginate:
  default: 10
  max: 50

# DATABASE
postgresql:
  client: pg
  connection:
    host: localhost
    user: unicorn_user
    password: magical_password
    database: rainbow_database
    port: 5432
  pool: 
    min: 0
    max: 10
    idleTimeoutMillis: 5000
  #   createTimeoutMillis: 30000
  #   acquireTimeoutMillis: 60000
  debug: true

# API KEYS
openai: 
  key: sk-XXXXXXXXXXXXXXXXXXXXXXXXXXX
  # MODEL OPTIONS
  max_tokens_llm: 4000
  use_proxy: false
  proxy_port: 8888
  stream: true

# TESTING
debug: false
verbose: false

storage:
  bucket: sample-bucket2
  apiEndpoint: http://127.0.0.1:9023
  local: true
  projectId: test

uploads:
  embeddingModel: text-embedding-3-small 

  
authentication:
  entity: user
  service: users
  secret: Z5EMUOsgs9oQ8+6Otfy8eNc6DRTU3L5O
  authStrategies:
    - jwt
    - local
    - googleIAP
  jwtOptions:
    header:
      typ: access
    audience: https://yourdomain.com
    algorithm: HS256
    expiresIn: 1d
  local:
    usernameField: email
    passwordField: password
  googleIAP:
    emailField: email
    idField: googleId