name: Contract Tests

on:
  push:
    branches:
      - dockertest

env:
  WORKDIR: "./"
  FILE: ".cicd/contract.docker-compose.yml"
  ENTRYPOINT: "entrypoint-command"
  SERVICE: "newman"
  COMMAND: run /etc/newman/contract.collection.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '2.14.2'
      
      - name: Start stack
        shell: bash
        run: |
          ls -la
          pwd
          cd ${{ env.WORKDIR }}
          docker-compose -f ${{ env.FILE }} pull --include-deps database storage api
          docker-compose -f ${{ env.FILE }} up -d database storage api

      - name: Test
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          DIR=$(pwd)
          docker-compose -f ${{ env.FILE }} run -v ${DIR}:/github_workspace -w /github_workspace --entrypoint ${{ env.ENTRYPOINT }} --rm ${{ env.SERVICE }} -- ${{ env.COMMAND }}

      - name: Stop stacks
        if: always()
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          docker-compose -f ${{ env.FILE }} down