name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main", "develop", "test" ]

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    environment: ${{ github.ref_name }}
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Outputs
        run: |-
          echo "env: ${{ toJson(env) }}"
          echo "vars: ${{ toJson(vars) }}"
          echo "ref: ${{ github.ref_name }}"

      - name: Build and Push Container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}
          registry: ${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ vars.AR_REPO }}
          image_name: ${{ env.SERVICE }}
          image_tag: ${{ github.sha }}

      - name: Authenticate with Google
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          
      - name: Inject Google Secret
        run: |-
          SECRET_ENV=${{ github.ref_name == 'main' && 'production' || github.ref_name }}
          gcloud secrets versions access latest --secret "${SECRET_ENV}-env-overrides" > ./config/local.yml;
          cd config;
          ls -la;
          echo "Contents of local.yml";
          cat local.yml;

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2.0.0
        with:
          project_id: ${{ vars.PROJECT_ID }}
          service: ${{ vars.SERVICE }}
          region: ${{ vars.REGION }}
          image: ${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.AR_REPO }}/${{ vars.SERVICE }}:${{ github.sha }}
          env_vars: |
            NODE_CONFIG_ENV=${{ github.ref_name == 'main' && 'production' || github.ref_name }}

          
