name: Contract Tests

on:
  workflow_call:
  workflow_dispatch:

env:
  WORKDIR: "./"
  FILE: "./test/contracts/contract.docker-compose.yml"
  ENTRYPOINT: "entrypoint-command"
  SERVICE: "newman"
  COMMAND: run /etc/newman/contract.collection.json
  DOCKER_REGISTRY: https://ghcr.io # the github registry

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start stack
        shell: bash
        run: |
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > .env
          docker compose --platform linux/amd64 --env-file ./.env -f ${{ env.FILE }} up --exit-code-from newman
        
      - name: Stop stacks
        if: always()
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          docker compose -f ${{ env.FILE }} down
