name: Test, Build, and Deploy to Cloud Run

on:
  push: 
    branches: 
      - '*'
      - '!develop'
      - '!test'
      - '!production'
      - '!main'

  workflow_dispatch:
    inputs:
      migration_input:
        description: 'Perform Migration'
        default: false
        required: true
        type: boolean
      seed_input:
        description: 'Perform Seed'
        default: false
        required: true
        type: boolean

jobs:
  contract-test:
    secrets: inherit
    uses: ./.github/workflows/job.contract-test.yml